name: Auto approve

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
        if: github.actor == 'scala-steward' || github.actor == 'renovate[bot]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
