name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
  JVM_OPTS: -XX:+PrintCommandLineFlags # for Java 8 only (sadly, it is not modern enough for JDK_JAVA_OPTIONS)

on:
  pull_request:
  push:
    branches: ['master']
  release:
    types:
      - published

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3.8.0
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Check code formatting
        run: ./sbt check

  compile:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: ['17']
        scala: ['2.12.17', '2.13.8', '3.2.0']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3.8.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Compile sources
        run: ./sbt ++${{ matrix.scala }}! compileSources

  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '11', '17']
        scala: ['2.12.17', '2.13.8', '3.2.0']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3.8.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Run tests
        run: ./sbt ++${{ matrix.scala }}! testAll

  publishLocal:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.1.0
      - name: Setup Java
        uses: actions/setup-java@v3.8.0
        with:
          distribution: temurin
          java-version: 8
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Check that building packages works
        run: ./sbt +publishLocal

  website:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.1.0
      - name: Setup Java
        uses: actions/setup-java@v3.8.0
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Check Website Generation
        run: ./sbt docs/docusaurusCreateSite

  ci:
    runs-on: ubuntu-20.04
    needs: [lint, compile, test, publishLocal, website]
    steps:
      - name: Aggregate outcomes
        run: echo "build succeeded"

  publish:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    needs: [ci]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3.8.0
        with:
          distribution: temurin
          java-version: 8
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Release artifacts
        run: ./sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
